kind: Pod
apiVersion: v1
metadata: 
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      project: expense
      enviorment: dev
      value: DevOps
    - name: trainer
      value: "mahesh"