kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    project: expense
    enviorment: dev
    component: backend
  ports:
    - procotol: TCP
      port: 80
      targetPort: 80

kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    project: expense
    enviroment: dev

spec:
  containers:
  - name: nginx
    image: nginx


  