kind: Pod
apiVersion: v1
metadata: 
  name: backend-np
  labels:
    project: expense
    environment: dev
    demo: np
spec:
  containers: 
  - name : nginx
    image: nginx

kind: Service
apiVersion: v1
metadata: 
  name: nginx-np
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
    demo: np
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    NodePort: 30007

